version: "3.9"
services:
  web:
    image: chiarorosa/app-node:1.0.2
    container_name: servidor-web
    networks:
      - compose-bridge
    ports:
      - 8080:3000

networks:
  compose-bridge:
    driver: bridge
