# Documentação https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"
services:
  web:
    image: chiarorosa/app-node:1.1
    container_name: node
    networks:
      - compose-bridge
    ports:
      - 8080:3000
    #depends_on:
    #  - serviceName

networks:
  compose-bridge:
    driver: bridge
